In [12]:
import pandas as pd

In [13]:
import numpy as np
import tensorflow as tf

In [ ]:
# pip install tensorflow

  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------

In [14]:
tf.__version__

'2.21.0'

In [15]:
dataset=pd.read_csv(r'C:\Users\beher\OneDrive\Desktop\DeepLearning\tensorflowkeras\Churn_Modelling (1).csv')

In [16]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [17]:
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1


In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [19]:
x

array([[619, 'delhi', 0, ..., 1, 1, 101348.88],
       [608, 'bangalore', 0, ..., 0, 1, 112542.58],
       [502, 'delhi', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 0, ..., 0, 1, 42085.58],
       [772, 'mumbai', 1, ..., 1, 0, 92888.52],
       [792, 'delhi', 0, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [21]:
x

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [23]:
x

array([[-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.74273971, -1.00280393, -0.57873591, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.57380915,  0.99720391, -0.57873591, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-0.57380915, -1.00280393,  1.72790383, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6)) # input 

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) # hiiden 1

In [29]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) # output

In [31]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
import warnings
warnings.filterwarnings('ignore')

In [32]:
ann.fit(x_train,y_train,batch_size=32,epochs=70)

Epoch 1/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6330 - loss: 0.6340
Epoch 2/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8019 - loss: 0.4636
Epoch 3/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8061 - loss: 0.4316
Epoch 4/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8169 - loss: 0.4168
Epoch 5/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8261 - loss: 0.4034
Epoch 6/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8360 - loss: 0.3885
Epoch 7/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8456 - loss: 0.3740
Epoch 8/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8531 - loss: 0.3626
Epoch 9/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8583 - loss: 0.3549
Epoch 10/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8595 - loss: 0.3506
Epoch 11/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8608 - loss: 0.3478
Epoch 12/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [41]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
# print(np.concatenate((y_pred.reshape(len(y_pred,1),y_test.reshape(len(y_test),1)),1)))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [42]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1504   91]
 [ 189  216]]


In [43]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
ac

0.86